from collections import deque
queue2=deque()
queue2.append("Wanjiku")
print(queue2)
print(type(queue2))
queue2.append("Nataly")
queue2.append("Gitahi")
queue2.append("Akwang")
queue2.append("Kantai")
queue2.append("Teresiah")
queue2.append("Daisy")
queue2.append("Naserian")
print(queue2)
queue2.appendleft("Wambui")
print(queue2)
queue2.popleft()
queue2.pop()
print(queue2)
print(queue2[2])
print(queue2[3])
print(queue2[0])
print(queue2[-1])
# from queue import queue
# queue1=queue(maxsize=4)
# print(queue1)
